package bootstrap

import (
	"context"
	"crypto/tls"
	"encoding/pem"
	"fmt"

	"github.com/prampec/trustmate/internal/keystore"
	"github.com/prampec/trustmate/internal/profiles"
	"github.com/prampec/trustmate/internal/store"
)

// LoadServerTLSConfig assembles the tls.Config the REST API listener
// terminates TLS with, from the server-tls leaf (and its issuing
// intermediate, for the chain) generated by Run. It works regardless of
// whether Run just bootstrapped that material or it already existed from
// an earlier run.
//
// Client-certificate verification is deliberately left at
// tls.NoClientCert: enforcing mTLS is Phase 3 per docs/design.md's
// roadmap, and Phase 0 has no protected admin route yet to gate.
func LoadServerTLSConfig(ctx context.Context, st store.Store, ks keystore.KeyStore) (*tls.Config, error) {
	leafRec, err := st.Certificates().GetLatestByProfile(ctx, profiles.ServerTLS().Name)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading server-tls certificate: %w", err)
	}
	interRecs, err := st.Certificates().FindByKind(ctx, store.CertKindIntermediate)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading intermediate certificate: %w", err)
	}
	if len(interRecs) == 0 {
		return nil, fmt.Errorf("bootstrap: no intermediate certificate found")
	}
	interRec := interRecs[len(interRecs)-1]

	leafDER, err := derFromPEM(leafRec.PEM)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: decoding server-tls PEM: %w", err)
	}
	interDER, err := derFromPEM(interRec.PEM)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: decoding intermediate PEM: %w", err)
	}

	signer, err := ks.Get(ctx, refServerTLS)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading server-tls private key: %w", err)
	}

	return &tls.Config{
		MinVersion: tls.VersionTLS12,
		ClientAuth: tls.NoClientCert, // TODO(phase 3): require/verify the admin mTLS client cert.
		Certificates: []tls.Certificate{{
			Certificate: [][]byte{leafDER, interDER},
			PrivateKey:  signer,
		}},
	}, nil
}

func derFromPEM(data []byte) ([]byte, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	return block.Bytes, nil
}
