package bootstrap

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"

	"github.com/prampec/trustmate/internal/keystore"
	"github.com/prampec/trustmate/internal/pki"
	"github.com/prampec/trustmate/internal/profiles"
	"github.com/prampec/trustmate/internal/store"
)

// LoadServerTLSConfig assembles the tls.Config the REST API listener
// terminates TLS with, from the server-tls leaf (and its issuing
// intermediate, for the chain) generated by Run. It works regardless of
// whether Run just bootstrapped that material or it already existed from
// an earlier run.
//
// ClientAuth is VerifyClientCertIfGiven, not RequireAndVerifyClientCert:
// several routes (/v1/crl, /v1/ocsp, /v1/tsa, /v1/ca/*.pem, /healthz,
// /readyz, /metrics) are meant to stay open to callers with no client
// cert at all. Any client cert that IS presented must chain to this CA
// (ClientCAs below) or the TLS handshake itself rejects it; per-route
// role requirements are then enforced in internal/api's requireRole
// middleware, which needs a verified peer certificate to look up a role
// for.
func LoadServerTLSConfig(ctx context.Context, st store.Store, ks keystore.KeyStore) (*tls.Config, error) {
	leafRec, err := st.Certificates().GetLatestByProfile(ctx, profiles.ServerTLS().Name)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading server-tls certificate: %w", err)
	}
	interRecs, err := st.Certificates().FindByKind(ctx, store.CertKindIntermediate)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading intermediate certificate: %w", err)
	}
	if len(interRecs) == 0 {
		return nil, fmt.Errorf("bootstrap: no intermediate certificate found")
	}
	interRec := interRecs[len(interRecs)-1]

	rootRecs, err := st.Certificates().FindByKind(ctx, store.CertKindRoot)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading root certificate: %w", err)
	}
	if len(rootRecs) == 0 {
		return nil, fmt.Errorf("bootstrap: no root certificate found")
	}
	rootRec := rootRecs[len(rootRecs)-1]

	leafDER, err := derFromPEM(leafRec.PEM)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: decoding server-tls PEM: %w", err)
	}
	interDER, err := derFromPEM(interRec.PEM)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: decoding intermediate PEM: %w", err)
	}

	signer, err := ks.Get(ctx, refServerTLS)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: loading server-tls private key: %w", err)
	}

	clientCAs := x509.NewCertPool()
	if !clientCAs.AppendCertsFromPEM(interRec.PEM) {
		return nil, fmt.Errorf("bootstrap: adding intermediate certificate to client CA pool")
	}
	if !clientCAs.AppendCertsFromPEM(rootRec.PEM) {
		return nil, fmt.Errorf("bootstrap: adding root certificate to client CA pool")
	}

	return &tls.Config{
		MinVersion: tls.VersionTLS12,
		ClientAuth: tls.VerifyClientCertIfGiven,
		ClientCAs:  clientCAs,
		Certificates: []tls.Certificate{{
			Certificate: [][]byte{leafDER, interDER},
			PrivateKey:  signer,
		}},
	}, nil
}

// LoadIntermediateIssuer reconstructs the intermediate CA's pki.Issuer
// (cert + signer) from the store and keystore at runtime, for use by
// anything that needs to sign with it after bootstrap -- e.g. leaf
// issuance, CRL generation, OCSP responses. Same "reconstruct
// bootstrap-generated material at runtime" role as LoadServerTLSConfig.
func LoadIntermediateIssuer(ctx context.Context, st store.Store, ks keystore.KeyStore) (pki.Issuer, error) {
	interRecs, err := st.Certificates().FindByKind(ctx, store.CertKindIntermediate)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: loading intermediate certificate: %w", err)
	}
	if len(interRecs) == 0 {
		return pki.Issuer{}, fmt.Errorf("bootstrap: no intermediate certificate found")
	}
	interRec := interRecs[len(interRecs)-1]

	interDER, err := derFromPEM(interRec.PEM)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: decoding intermediate PEM: %w", err)
	}
	cert, err := x509.ParseCertificate(interDER)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: parsing intermediate certificate: %w", err)
	}

	signer, err := ks.Get(ctx, IntermediateKeyRef)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: loading intermediate private key: %w", err)
	}

	return pki.Issuer{Cert: cert, Signer: signer}, nil
}

// LoadTSAIssuer reconstructs the TSA's own pki.Issuer (cert + signer)
// from the store and keystore at runtime -- same "reconstruct
// bootstrap-generated material" role as LoadIntermediateIssuer, but for
// the TSA's own signing identity rather than the intermediate CA. Only
// meaningful when the deployment bootstrapped with cfg.Modules.TSA true;
// callers should not invoke this otherwise.
func LoadTSAIssuer(ctx context.Context, st store.Store, ks keystore.KeyStore) (pki.Issuer, error) {
	rec, err := st.Certificates().GetLatestByProfile(ctx, profiles.TSA().Name)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: loading TSA certificate: %w", err)
	}

	der, err := derFromPEM(rec.PEM)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: decoding TSA PEM: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: parsing TSA certificate: %w", err)
	}

	signer, err := ks.Get(ctx, refTSA)
	if err != nil {
		return pki.Issuer{}, fmt.Errorf("bootstrap: loading TSA private key: %w", err)
	}

	return pki.Issuer{Cert: cert, Signer: signer}, nil
}

func derFromPEM(data []byte) ([]byte, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("no PEM block found")
	}
	return block.Bytes, nil
}
